CREATE TABLE IF NOT EXISTS user (
idUser int(11) NOT NULL,
  nom varchar(100) NOT NULL,
  email varchar(50) NOT NULL,
  password varchar(50) NOT NULL,
  isAdmin tinyint(4) NOT NULL DEFAULT 0,
  img varchar(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

--
ALTER TABLE user
 ADD PRIMARY KEY (idUser);

ALTER TABLE user
MODIFY idUser int(11) NOT NULL AUTO_INCREMENT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
